INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AFG', 'AF', 'Afghanistan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ALA', 'AX', 'Åland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ALB', 'AL', 'Albania');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DZA', 'DZ', 'Algeria');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ASM', 'AS', 'American Samoa');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AND', 'AD', 'Andorra');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AGO', 'AO', 'Angola');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AIA', 'AI', 'Anguilla');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ATA', 'AQ', 'Antarctica');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ATG', 'AG', 'Antigua and Barbuda');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ARG', 'AR', 'Argentina');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ARM', 'AM', 'Armenia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ABW', 'AW', 'Aruba');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AUS', 'AU', 'Australia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AUT', 'AT', 'Austria');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('AZE', 'AZ', 'Azerbaijan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BHS', 'BS', 'Bahamas');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BHR', 'BH', 'Bahrain');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BGD', 'BD', 'Bangladesh');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BRB', 'BB', 'Barbados');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BLR', 'BY', 'Belarus');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BEL', 'BE', 'Belgium');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BLZ', 'BZ', 'Belize');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BEN', 'BJ', 'Benin');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BMU', 'BM', 'Bermuda');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BTN', 'BT', 'Bhutan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BOL', 'BO', 'Bolivia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BES', 'BQ', 'Bonaire');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BIH', 'BA', 'Bosnia and Herzegovina');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BWA', 'BW', 'Botswana');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BVT', 'BV', 'Bouvet Island');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BRA', 'BR', 'Brazil');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IOT', 'IO', 'British Indian Ocean Territory');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VGB', 'VG', 'British Virgin Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BRN', 'BN', 'Brunei');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BGR', 'BG', 'Bulgaria');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BFA', 'BF', 'Burkina Faso');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BDI', 'BI', 'Burundi');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KHM', 'KH', 'Cambodia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CMR', 'CM', 'Cameroon');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CAN', 'CA', 'Canada');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CPV', 'CV', 'Cape Verde');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CYM', 'KY', 'Cayman Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CAF', 'CF', 'Central African Republic');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TCD', 'TD', 'Chad');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CHL', 'CL', 'Chile');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CHN', 'CN', 'China');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CXR', 'CX', 'Christmas Island');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CCK', 'CC', 'Cocos [Keeling] Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('COL', 'CO', 'Colombia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('COM', 'KM', 'Comoros');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('COK', 'CK', 'Cook Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CRI', 'CR', 'Costa Rica');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HRV', 'HR', 'Croatia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CUB', 'CU', 'Cuba');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CUW', 'CW', 'Curacao');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CYP', 'CY', 'Cyprus');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CZE', 'CZ', 'Czech Republic');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('COD', 'CD', 'Democratic Republic of the Congo');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DNK', 'DK', 'Denmark');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DJI', 'DJ', 'Djibouti');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DMA', 'DM', 'Dominica');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DOM', 'DO', 'Dominican Republic');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TLS', 'TL', 'East Timor');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ECU', 'EC', 'Ecuador');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('EGY', 'EG', 'Egypt');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SLV', 'SV', 'El Salvador');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GNQ', 'GQ', 'Equatorial Guinea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ERI', 'ER', 'Eritrea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('EST', 'EE', 'Estonia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ETH', 'ET', 'Ethiopia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FLK', 'FK', 'Falkland Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FRO', 'FO', 'Faroe Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FJI', 'FJ', 'Fiji');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FIN', 'FI', 'Finland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FRA', 'FR', 'France');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GUF', 'GF', 'French Guiana');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PYF', 'PF', 'French Polynesia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ATF', 'TF', 'French Southern Territories');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GAB', 'GA', 'Gabon');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GMB', 'GM', 'Gambia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GEO', 'GE', 'Georgia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('DEU', 'DE', 'Germany');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GHA', 'GH', 'Ghana');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GIB', 'GI', 'Gibraltar');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GRC', 'GR', 'Greece');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GRL', 'GL', 'Greenland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GRD', 'GD', 'Grenada');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GLP', 'GP', 'Guadeloupe');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GUM', 'GU', 'Guam');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GTM', 'GT', 'Guatemala');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GGY', 'GG', 'Guernsey');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GIN', 'GN', 'Guinea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GNB', 'GW', 'Guinea-Bissau');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GUY', 'GY', 'Guyana');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HTI', 'HT', 'Haiti');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HMD', 'HM', 'Heard Island and McDonald Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HND', 'HN', 'Honduras');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HKG', 'HK', 'Hong Kong');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('HUN', 'HU', 'Hungary');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ISL', 'IS', 'Iceland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IND', 'IN', 'India');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IDN', 'ID', 'Indonesia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IRN', 'IR', 'Iran');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IRQ', 'IQ', 'Iraq');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IRL', 'IE', 'Ireland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('IMN', 'IM', 'Isle of Man');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ISR', 'IL', 'Israel');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ITA', 'IT', 'Italy');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CIV', 'CI', 'Ivory Coast');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('JAM', 'JM', 'Jamaica');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('JPN', 'JP', 'Japan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('JEY', 'JE', 'Jersey');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('JOR', 'JO', 'Jordan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KAZ', 'KZ', 'Kazakhstan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KEN', 'KE', 'Kenya');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KIR', 'KI', 'Kiribati');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('XKX', 'XK', 'Kosovo');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KWT', 'KW', 'Kuwait');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KGZ', 'KG', 'Kyrgyzstan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LAO', 'LA', 'Laos');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LVA', 'LV', 'Latvia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LBN', 'LB', 'Lebanon');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LSO', 'LS', 'Lesotho');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LBR', 'LR', 'Liberia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LBY', 'LY', 'Libya');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LIE', 'LI', 'Liechtenstein');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LTU', 'LT', 'Lithuania');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LUX', 'LU', 'Luxembourg');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MAC', 'MO', 'Macao');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MKD', 'MK', 'Macedonia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MDG', 'MG', 'Madagascar');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MWI', 'MW', 'Malawi');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MYS', 'MY', 'Malaysia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MDV', 'MV', 'Maldives');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MLI', 'ML', 'Mali');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MLT', 'MT', 'Malta');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MHL', 'MH', 'Marshall Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MTQ', 'MQ', 'Martinique');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MRT', 'MR', 'Mauritania');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MUS', 'MU', 'Mauritius');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MYT', 'YT', 'Mayotte');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MEX', 'MX', 'Mexico');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('FSM', 'FM', 'Micronesia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MDA', 'MD', 'Moldova');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MCO', 'MC', 'Monaco');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MNG', 'MN', 'Mongolia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MNE', 'ME', 'Montenegro');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MSR', 'MS', 'Montserrat');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MAR', 'MA', 'Morocco');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MOZ', 'MZ', 'Mozambique');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MMR', 'MM', 'Myanmar [Burma]');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NAM', 'NA', 'Namibia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NRU', 'NR', 'Nauru');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NPL', 'NP', 'Nepal');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NLD', 'NL', 'Netherlands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NCL', 'NC', 'New Caledonia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NZL', 'NZ', 'New Zealand');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NIC', 'NI', 'Nicaragua');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NER', 'NE', 'Niger');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NGA', 'NG', 'Nigeria');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NIU', 'NU', 'Niue');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NFK', 'NF', 'Norfolk Island');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PRK', 'KP', 'North Korea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MNP', 'MP', 'Northern Mariana Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('NOR', 'NO', 'Norway');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('OMN', 'OM', 'Oman');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PAK', 'PK', 'Pakistan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PLW', 'PW', 'Palau');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PSE', 'PS', 'Palestine');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PAN', 'PA', 'Panama');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PNG', 'PG', 'Papua New Guinea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PRY', 'PY', 'Paraguay');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PER', 'PE', 'Peru');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PHL', 'PH', 'Philippines');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PCN', 'PN', 'Pitcairn Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('POL', 'PL', 'Poland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PRT', 'PT', 'Portugal');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('PRI', 'PR', 'Puerto Rico');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('QAT', 'QA', 'Qatar');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('COG', 'CG', 'Republic of the Congo');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('REU', 'RE', 'Réunion');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ROU', 'RO', 'Romania');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('RUS', 'RU', 'Russia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('RWA', 'RW', 'Rwanda');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('BLM', 'BL', 'Saint Barthélemy');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SHN', 'SH', 'Saint Helena');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KNA', 'KN', 'Saint Kitts and Nevis');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LCA', 'LC', 'Saint Lucia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('MAF', 'MF', 'Saint Martin');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SPM', 'PM', 'Saint Pierre and Miquelon');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VCT', 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('WSM', 'WS', 'Samoa');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SMR', 'SM', 'San Marino');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('STP', 'ST', 'São Tomé and Príncipe');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SAU', 'SA', 'Saudi Arabia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SEN', 'SN', 'Senegal');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SRB', 'RS', 'Serbia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SYC', 'SC', 'Seychelles');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SLE', 'SL', 'Sierra Leone');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SGP', 'SG', 'Singapore');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SXM', 'SX', 'Sint Maarten');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SVK', 'SK', 'Slovakia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SVN', 'SI', 'Slovenia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SLB', 'SB', 'Solomon Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SOM', 'SO', 'Somalia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ZAF', 'ZA', 'South Africa');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SGS', 'GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('KOR', 'KR', 'South Korea');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SSD', 'SS', 'South Sudan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ESP', 'ES', 'Spain');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('LKA', 'LK', 'Sri Lanka');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SDN', 'SD', 'Sudan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SUR', 'SR', 'Suriname');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SJM', 'SJ', 'Svalbard and Jan Mayen');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SWZ', 'SZ', 'Swaziland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SWE', 'SE', 'Sweden');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('CHE', 'CH', 'Switzerland');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('SYR', 'SY', 'Syria');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TWN', 'TW', 'Taiwan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TJK', 'TJ', 'Tajikistan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TZA', 'TZ', 'Tanzania');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('THA', 'TH', 'Thailand');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TGO', 'TG', 'Togo');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TKL', 'TK', 'Tokelau');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TON', 'TO', 'Tonga');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TTO', 'TT', 'Trinidad and Tobago');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TUN', 'TN', 'Tunisia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TUR', 'TR', 'Turkey');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TKM', 'TM', 'Turkmenistan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TCA', 'TC', 'Turks and Caicos Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('TUV', 'TV', 'Tuvalu');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('UMI', 'UM', 'U.S. Minor Outlying Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VIR', 'VI', 'U.S. Virgin Islands');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('UGA', 'UG', 'Uganda');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('UKR', 'UA', 'Ukraine');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ARE', 'AE', 'United Arab Emirates');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('GBR', 'GB', 'United Kingdom');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('USA', 'US', 'United States');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('URY', 'UY', 'Uruguay');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('UZB', 'UZ', 'Uzbekistan');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VUT', 'VU', 'Vanuatu');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VAT', 'VA', 'Vatican City');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VEN', 'VE', 'Venezuela');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('VNM', 'VN', 'Vietnam');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('WLF', 'WF', 'Wallis and Futuna');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ESH', 'EH', 'Western Sahara');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('YEM', 'YE', 'Yemen');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ZMB', 'ZM', 'Zambia');
INSERT INTO public.etlcountry
(country_code, code, country_name)
VALUES('ZWE', 'ZW', 'Zimbabwe');