# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.7"
# Define services
services:
  # Backend AccessService's
  # auth service
  auth-service:
    # Configuration for building the docker image for the backend service
    build:
      context: auth # Use an image built from the specified dockerfile in the `auth` directory.
      dockerfile: Dockerfile
    ports:
      - "9095:9095" # Forward the exposed port 9095 on the container to port 9095 on the host machine
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # admin-api service
  admin-api-service:
    # Configuration for building the docker image for the backend service
    build:
      context: admin-api # Use an image built from the specified dockerfile in the `admin-api` directory.
      dockerfile: Dockerfile
    ports:
      - "9096:9096" # Forward the exposed port 9096 on the container to port 9096 on the host machine
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # service-1 service
  service-1-service:
    # Configuration for building the docker image for the backend service
    build:
      context: service-1 # Use an image built from the specified dockerfile in the `service-1` directory.
      dockerfile: Dockerfile
    ports:
      - "9097:9097" # Forward the exposed port 9097 on the container to port 9097 on the host machine
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # service-2 service
  service-2-service:
    # Configuration for building the docker image for the backend service
    build:
      context: service-2 # Use an image built from the specified dockerfile in the `service-2` directory.
      dockerfile: Dockerfile
    ports:
      - "9098:9098" # Forward the exposed port 9098 on the container to port 9098 on the host machine
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # service-3 service
  service-3-service:
    # Configuration for building the docker image for the backend service
    build:
      context: service-3 # Use an image built from the specified dockerfile in the `service-3` directory.
      dockerfile: Dockerfile
    ports:
      - "9099:9099" # Forward the exposed port 9099 on the container to port 9099 on the host machine
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  # Database AccessService
  db:
    image: postgres:9.4 # Pull postgress image
    volumes:
      - db-data:/var/lib/postgresql/data # persist data even if container shuts down
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
# Volumes
volumes:
  db-data:
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:

# Start compose
#  docker-compose up
# Stip compose
# docker-compose down
