-- Default Authority Script ---
--insert into authority values(1000, current_date, 0, 1, current_date,0,'ROLE_SUPER_ADIM');
--insert into authority values (1001, current_date, 0, 1, current_date,0,'ROLE_ADMIN');
--insert into authority values (1002, current_date, 0, 1, current_date,0,'ROLE_USER');
-- Default Acess Service Script
--insert into access_service values (1000, current_date, 0, 1, current_date, 0, 'Service-1', 'WebScraping');
--insert into access_service values (1002, current_date, 0, 1, current_date, 0, 'Service-2', 'DataFetch');
--insert into access_service values (1003, current_date, 0, 1, current_date, 0, 'Service-3', 'FireStream');

--================================Local User Script====================
--select * from app_user;
--select * from public.authority;
--select * from user_verification;
--select * from public.user_authority
--delete from public.app_user where id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.app_user where parent_user_id = 1026
--delete from PUBLIC.user_authority where user_id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.notification_client where app_user_id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.user_verification where app_user_id in (1027,1028,1029,1030,1031,1032);
--delete from app_sub_user where app_sub_user.parent_user_id = 1018
--select * from app_sub_user
--select * from public.app_sub_user
--select * from app_user where app_user.created_by_id = 1018 and id not in (1033,1034,1035,1036,1037)
--select * from public.app_user where app_user.created_by_id = 1018
--
--
--// delete user will not show inactive and pending user can be sow on the table view
--select ap_us.id, ap_us.first_name || ' ' || ap_us.last_name as full_name, ap_us.username, auth.role, ap_us.status, ap_us.user_type
--from app_user as ap_us
--  inner join user_authority as us_auth on ap_us.id = us_auth.user_id
--  inner join authority as auth on auth.id = us_auth.authority_id
--  inner join app_sub_user as ap_su on ap_su.parent_user_id = ap_us.created_by_id
--where ap_su.parent_user_id = 1018 group by ap_us.id, auth.role;
--

--select jb.id, jb.job_name, tk.id, tk.task_name, jb.is_disabled,
--       jb.execution_type, jb.is_disabled, jb.job_status, jb.last_job_run,
--       jb.next_job_run, jb.skip_job_run
--from job as jb
--  left join task as tk on tk.id = jb.task_id
--where tk.created_by_id = 1018
--
--select tk.id, tk.task_name, tk.class_name as service_name,
--       tk.created_at, tk.modified_at, tk.status, count(jb.id) as jb_attache, sd.storage_key_name
--from public.task as tk
--  left join public.job as jb on jb.task_id = tk.id
--  left join public.storage_detail as sd on sd.id = tk.storage_id
--where tk.created_by_id = 1018
--group by tk.id, sd.id
--
--select sd.id, sd.key_type, sd.storage_key_name, count(tk.storage_id) as tk_attache,
--       sd.status, sd.created_at, sd.modified_at
--from public.storage_detail sd
--  left join task tk on tk.storage_id = sd.id
--where sd.created_by_id = 1018
--group by sd.id

