-- Default Authority Script ---
--insert into authority values(1, current_date, 0, 1, current_date,0,'ROLE_SUPER_ADIM');
--insert into authority values (2, current_date, 0, 1, current_date,0,'ROLE_ADMIN');
--insert into authority values (3, current_date, 0, 1, current_date,0,'ROLE_USER');
---- Default Task Script ---
--INSERT INTO task (id, created_at, created_by_id, status, modified_at, modified_by_id, class_name)
--VALUES (1, current_date, 0, 1, current_date, 0, 'SegmentProcessTask');
--INSERT INTO task (id, created_at, created_by_id, status, modified_at, modified_by_id, class_name)
--VALUES (2, current_date, 0, 1, current_date, 0, 'WebScrapingProcessTask');
--INSERT INTO task (id, created_at, created_by_id, status, modified_at, modified_by_id, class_name)
--VALUES (3, current_date, 0, 1, current_date, 0, 'StockPriceProcessTask');
--INSERT INTO task (id, created_at, created_by_id, status, modified_at, modified_by_id, class_name)
--VALUES (4, current_date, 0, 1, current_date, 0, 'PublishArticlesProcessTask');
--INSERT INTO task (id, created_at, created_by_id, status, modified_at, modified_by_id, class_name)
--VALUES (1, current_date, 0, 1, current_date, 0, 'HelloWordTask');

--http://localhost:8080/signup-success?token=scheduler-72943313861000000000&username=Nabeel%20Ahmed
-- dander query user only when neeed
--drop table user_authority;
--drop table user_verification
--drop table authority;
--drop table batch_file_process;
--drop table batch_job;
--drop table batch_job_logs;
--drop table file_info;
--drop table job_queue;
--drop table key;
--drop table notification_detail;
--drop table scheduler;
--drop table socket_client_info;
--drop table stock_price;
--drop table job;
--drop table notification_client;
--drop table task;
--drop table app_user;


--select * from app_user;
--select * from public.authority;
--select * from user_verification;
--select * from public.user_authority
--delete from public.app_user where id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.app_user where parent_user_id = 1026
--delete from PUBLIC.user_authority where user_id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.notification_client where app_user_id in (1027,1028,1029,1030,1031,1032);
--delete from PUBLIC.user_verification where app_user_id in (1027,1028,1029,1030,1031,1032);
--delete from app_sub_user where app_sub_user.parent_user_id = 1018
--select * from app_sub_user
--select * from public.app_sub_user
--select * from app_user where app_user.created_by_id = 1018 and id not in (1033,1034,1035,1036,1037)
--select * from public.app_user where app_user.created_by_id = 1018
--
--
--// delete user will not show inactive and pending user can be sow on the table view
--select ap_us.id, ap_us.first_name || ' ' || ap_us.last_name as full_name, ap_us.username, auth.role, ap_us.status, ap_us.user_type
--from app_user as ap_us
--  inner join user_authority as us_auth on ap_us.id = us_auth.user_id
--  inner join authority as auth on auth.id = us_auth.authority_id
--  inner join app_sub_user as ap_su on ap_su.parent_user_id = ap_us.created_by_id
--where ap_su.parent_user_id = 1018 group by ap_us.id, auth.role;
--
