--Admin - admin:123
--User - user:123
-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
--INSERT INTO app_user(id,created_at,status,address,company_name,first_name,image_url,last_name,mobile,password,username)
--VALUES (1,current_timestamp,1,'B3rd-2561 Lahore','Ballistic','Nabeel','https://avatars1.githubusercontent.com/u/24192325?s=400&u=eb9d26871b1b873497f4f71df76d70fa7e046194&v=4',
--'Ahmed','+92-3153817177','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra','nabeel.amd93@gmail.com');

--INSERT INTO app_user
--(id,created_at,status,address,company_name,first_name,image_url,last_name,mobile,password,username)
--VALUES (2,current_timestamp,1,'B3rd-2561 Lahore','Ballistic','Nabeel','https://avatars1.githubusercontent.com/u/24192325?s=400&u=eb9d26871b1b873497f4f71df76d70fa7e046194&v=4',
--'Ahmed','+92-3153817178','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra','nabeel.amd931@gmail.com');

--INSERT INTO authority (id, role, created_at, created_by_id, status) VALUES (1, 'ROLE_USER', current_timestamp, 0, 1);
--INSERT INTO authority (id, role, created_at, created_by_id, status) VALUES (2, 'ROLE_ADMIN', current_timestamp, 0, 1);

--INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
--INSERT INTO user_authority (user_id, authority_id) VALUES (2, 1);
--INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);