INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('AFG','AF','Afghanistan'),
	 ('ALA','AX','Åland'),
	 ('ALB','AL','Albania'),
	 ('DZA','DZ','Algeria'),
	 ('ASM','AS','American Samoa'),
	 ('AND','AD','Andorra'),
	 ('AGO','AO','Angola'),
	 ('AIA','AI','Anguilla'),
	 ('ATA','AQ','Antarctica'),
	 ('ATG','AG','Antigua and Barbuda');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('ARG','AR','Argentina'),
	 ('ARM','AM','Armenia'),
	 ('ABW','AW','Aruba'),
	 ('AUS','AU','Australia'),
	 ('AUT','AT','Austria'),
	 ('AZE','AZ','Azerbaijan'),
	 ('BHS','BS','Bahamas'),
	 ('BHR','BH','Bahrain'),
	 ('BGD','BD','Bangladesh'),
	 ('BRB','BB','Barbados');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('BLR','BY','Belarus'),
	 ('BEL','BE','Belgium'),
	 ('BLZ','BZ','Belize'),
	 ('BEN','BJ','Benin'),
	 ('BMU','BM','Bermuda'),
	 ('BTN','BT','Bhutan'),
	 ('BOL','BO','Bolivia'),
	 ('BES','BQ','Bonaire'),
	 ('BIH','BA','Bosnia and Herzegovina'),
	 ('BWA','BW','Botswana');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('BVT','BV','Bouvet Island'),
	 ('BRA','BR','Brazil'),
	 ('IOT','IO','British Indian Ocean Territory'),
	 ('VGB','VG','British Virgin Islands'),
	 ('BRN','BN','Brunei'),
	 ('BGR','BG','Bulgaria'),
	 ('BFA','BF','Burkina Faso'),
	 ('BDI','BI','Burundi'),
	 ('KHM','KH','Cambodia'),
	 ('CMR','CM','Cameroon');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('CAN','CA','Canada'),
	 ('CPV','CV','Cape Verde'),
	 ('CYM','KY','Cayman Islands'),
	 ('CAF','CF','Central African Republic'),
	 ('TCD','TD','Chad'),
	 ('CHL','CL','Chile'),
	 ('CHN','CN','China'),
	 ('CXR','CX','Christmas Island'),
	 ('CCK','CC','Cocos [Keeling] Islands'),
	 ('COL','CO','Colombia');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('COM','KM','Comoros'),
	 ('COK','CK','Cook Islands'),
	 ('CRI','CR','Costa Rica'),
	 ('HRV','HR','Croatia'),
	 ('CUB','CU','Cuba'),
	 ('CUW','CW','Curacao'),
	 ('CYP','CY','Cyprus'),
	 ('CZE','CZ','Czech Republic'),
	 ('COD','CD','Democratic Republic of the Congo'),
	 ('DNK','DK','Denmark');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('DJI','DJ','Djibouti'),
	 ('DMA','DM','Dominica'),
	 ('DOM','DO','Dominican Republic'),
	 ('TLS','TL','East Timor'),
	 ('ECU','EC','Ecuador'),
	 ('EGY','EG','Egypt'),
	 ('SLV','SV','El Salvador'),
	 ('GNQ','GQ','Equatorial Guinea'),
	 ('ERI','ER','Eritrea'),
	 ('EST','EE','Estonia');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('ETH','ET','Ethiopia'),
	 ('FLK','FK','Falkland Islands'),
	 ('FRO','FO','Faroe Islands'),
	 ('FJI','FJ','Fiji'),
	 ('FIN','FI','Finland'),
	 ('FRA','FR','France'),
	 ('GUF','GF','French Guiana'),
	 ('PYF','PF','French Polynesia'),
	 ('ATF','TF','French Southern Territories'),
	 ('GAB','GA','Gabon');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('GMB','GM','Gambia'),
	 ('GEO','GE','Georgia'),
	 ('DEU','DE','Germany'),
	 ('GHA','GH','Ghana'),
	 ('GIB','GI','Gibraltar'),
	 ('GRC','GR','Greece'),
	 ('GRL','GL','Greenland'),
	 ('GRD','GD','Grenada'),
	 ('GLP','GP','Guadeloupe'),
	 ('GUM','GU','Guam');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('GTM','GT','Guatemala'),
	 ('GGY','GG','Guernsey'),
	 ('GIN','GN','Guinea'),
	 ('GNB','GW','Guinea-Bissau'),
	 ('GUY','GY','Guyana'),
	 ('HTI','HT','Haiti'),
	 ('HMD','HM','Heard Island and McDonald Islands'),
	 ('HND','HN','Honduras'),
	 ('HKG','HK','Hong Kong'),
	 ('HUN','HU','Hungary');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('ISL','IS','Iceland'),
	 ('IND','IN','India'),
	 ('IDN','ID','Indonesia'),
	 ('IRN','IR','Iran'),
	 ('IRQ','IQ','Iraq'),
	 ('IRL','IE','Ireland'),
	 ('IMN','IM','Isle of Man'),
	 ('ISR','IL','Israel'),
	 ('ITA','IT','Italy'),
	 ('CIV','CI','Ivory Coast');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('JAM','JM','Jamaica'),
	 ('JPN','JP','Japan'),
	 ('JEY','JE','Jersey'),
	 ('JOR','JO','Jordan'),
	 ('KAZ','KZ','Kazakhstan'),
	 ('KEN','KE','Kenya'),
	 ('KIR','KI','Kiribati'),
	 ('XKX','XK','Kosovo'),
	 ('KWT','KW','Kuwait'),
	 ('KGZ','KG','Kyrgyzstan');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('LAO','LA','Laos'),
	 ('LVA','LV','Latvia'),
	 ('LBN','LB','Lebanon'),
	 ('LSO','LS','Lesotho'),
	 ('LBR','LR','Liberia'),
	 ('LBY','LY','Libya'),
	 ('LIE','LI','Liechtenstein'),
	 ('LTU','LT','Lithuania'),
	 ('LUX','LU','Luxembourg'),
	 ('MAC','MO','Macao');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('MKD','MK','Macedonia'),
	 ('MDG','MG','Madagascar'),
	 ('MWI','MW','Malawi'),
	 ('MYS','MY','Malaysia'),
	 ('MDV','MV','Maldives'),
	 ('MLI','ML','Mali'),
	 ('MLT','MT','Malta'),
	 ('MHL','MH','Marshall Islands'),
	 ('MTQ','MQ','Martinique'),
	 ('MRT','MR','Mauritania');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('MUS','MU','Mauritius'),
	 ('MYT','YT','Mayotte'),
	 ('MEX','MX','Mexico'),
	 ('FSM','FM','Micronesia'),
	 ('MDA','MD','Moldova'),
	 ('MCO','MC','Monaco'),
	 ('MNG','MN','Mongolia'),
	 ('MNE','ME','Montenegro'),
	 ('MSR','MS','Montserrat'),
	 ('MAR','MA','Morocco');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('MOZ','MZ','Mozambique'),
	 ('MMR','MM','Myanmar [Burma]'),
	 ('NAM','NA','Namibia'),
	 ('NRU','NR','Nauru'),
	 ('NPL','NP','Nepal'),
	 ('NLD','NL','Netherlands'),
	 ('NCL','NC','New Caledonia'),
	 ('NZL','NZ','New Zealand'),
	 ('NIC','NI','Nicaragua'),
	 ('NER','NE','Niger');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('NGA','NG','Nigeria'),
	 ('NIU','NU','Niue'),
	 ('NFK','NF','Norfolk Island'),
	 ('PRK','KP','North Korea'),
	 ('MNP','MP','Northern Mariana Islands'),
	 ('NOR','NO','Norway'),
	 ('OMN','OM','Oman'),
	 ('PAK','PK','Pakistan'),
	 ('PLW','PW','Palau'),
	 ('PSE','PS','Palestine');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('PAN','PA','Panama'),
	 ('PNG','PG','Papua New Guinea'),
	 ('PRY','PY','Paraguay'),
	 ('PER','PE','Peru'),
	 ('PHL','PH','Philippines'),
	 ('PCN','PN','Pitcairn Islands'),
	 ('POL','PL','Poland'),
	 ('PRT','PT','Portugal'),
	 ('PRI','PR','Puerto Rico'),
	 ('QAT','QA','Qatar');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('COG','CG','Republic of the Congo'),
	 ('REU','RE','Réunion'),
	 ('ROU','RO','Romania'),
	 ('RUS','RU','Russia'),
	 ('RWA','RW','Rwanda'),
	 ('BLM','BL','Saint Barthélemy'),
	 ('SHN','SH','Saint Helena'),
	 ('KNA','KN','Saint Kitts and Nevis'),
	 ('LCA','LC','Saint Lucia'),
	 ('MAF','MF','Saint Martin');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('SPM','PM','Saint Pierre and Miquelon'),
	 ('VCT','VC','Saint Vincent and the Grenadines'),
	 ('WSM','WS','Samoa'),
	 ('SMR','SM','San Marino'),
	 ('STP','ST','São Tomé and Príncipe'),
	 ('SAU','SA','Saudi Arabia'),
	 ('SEN','SN','Senegal'),
	 ('SRB','RS','Serbia'),
	 ('SYC','SC','Seychelles'),
	 ('SLE','SL','Sierra Leone');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('SGP','SG','Singapore'),
	 ('SXM','SX','Sint Maarten'),
	 ('SVK','SK','Slovakia'),
	 ('SVN','SI','Slovenia'),
	 ('SLB','SB','Solomon Islands'),
	 ('SOM','SO','Somalia'),
	 ('ZAF','ZA','South Africa'),
	 ('SGS','GS','South Georgia and the South Sandwich Islands'),
	 ('KOR','KR','South Korea'),
	 ('SSD','SS','South Sudan');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('ESP','ES','Spain'),
	 ('LKA','LK','Sri Lanka'),
	 ('SDN','SD','Sudan'),
	 ('SUR','SR','Suriname'),
	 ('SJM','SJ','Svalbard and Jan Mayen'),
	 ('SWZ','SZ','Swaziland'),
	 ('SWE','SE','Sweden'),
	 ('CHE','CH','Switzerland'),
	 ('SYR','SY','Syria'),
	 ('TWN','TW','Taiwan');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('TJK','TJ','Tajikistan'),
	 ('TZA','TZ','Tanzania'),
	 ('THA','TH','Thailand'),
	 ('TGO','TG','Togo'),
	 ('TKL','TK','Tokelau'),
	 ('TON','TO','Tonga'),
	 ('TTO','TT','Trinidad and Tobago'),
	 ('TUN','TN','Tunisia'),
	 ('TUR','TR','Turkey'),
	 ('TKM','TM','Turkmenistan');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('TCA','TC','Turks and Caicos Islands'),
	 ('TUV','TV','Tuvalu'),
	 ('UMI','UM','U.S. Minor Outlying Islands'),
	 ('VIR','VI','U.S. Virgin Islands'),
	 ('UGA','UG','Uganda'),
	 ('UKR','UA','Ukraine'),
	 ('ARE','AE','United Arab Emirates'),
	 ('GBR','GB','United Kingdom'),
	 ('USA','US','United States'),
	 ('URY','UY','Uruguay');
INSERT INTO public.etlcountry (country_code,code,country_name) VALUES
	 ('UZB','UZ','Uzbekistan'),
	 ('VUT','VU','Vanuatu'),
	 ('VAT','VA','Vatican City'),
	 ('VEN','VE','Venezuela'),
	 ('VNM','VN','Vietnam'),
	 ('WLF','WF','Wallis and Futuna'),
	 ('ESH','EH','Western Sahara'),
	 ('YEM','YE','Yemen'),
	 ('ZMB','ZM','Zambia'),
	 ('ZWE','ZW','Zimbabwe');
