package com.barco.model.enums;

/**
 * @author Nabeel Ahmed
 */
public enum ApiCode {
    SUCCESS,
    INVALID_REQUEST,
    ERROR,
    ALREADY_CONSUMED,
    HTTP_400,
    HTTP_500,
    HTTP_404,
    DELETED,
    INVALID_CREDENTIAL,
    UNREGISTERED_EMAIL,
    INACTIVE_USER,
    PENDING,
    INVALID_VERIFICATION_TOKEN,
    EMAIL_VALIDATION_TIME,
    VERIFICATION_TOKEN_CONSUMED,
    INVALID_VERIFICATION_PASSWORD,
    INVALID_EMAIL_PATTREN,
    PASSWORD_UNSCURE,
    DUPLICATE_EMAIL,
    DUPLICATE_CAMPAIGN_NAME,
    DUPLICATE_COMPANY_NAME,
    DUPLICATE_RECORD,
    VALIDATION_ERROR,
}
